statuses:
  { [ { created_at: 'Sun Feb 17 00:37:47 +0000 2019',
       id: 1096931683268476900,
       id_str: '1096931683268476933',
       text:
        'About to pop into @NBAonTNT and talk #AllStarWeekend and my performance tomorrow at the game 🏆',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 373,
       favorite_count: 3167,
       favorited: false,
       retweeted: false,
       lang: 'en' },
     { created_at: 'Sun Feb 17 03:12:24 +0000 2019',
       id: 1096970590173388800,
       id_str: '1096970590173388800',
       text:
        'Steph Curry is wearing the same windbreaker he wore during the 1992 #AllStarWeekend this is damn adorable https://t.co/7i5ksPtVT4',
       truncated: false,
       entities: [Object],
       extended_entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 469,
       favorite_count: 1458,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun Feb 17 02:18:44 +0000 2019',
       id: 1096957085609312300,
       id_str: '1096957085609312257',
       text:
        'I’ve been watching basketball since the 70’s. I’ve seen a lot of things. I’ve not ever seen anyone shoot the ball t… https://t.co/gyH3caD1s4',
       truncated: true,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 84,
       favorite_count: 1022,
       favorited: false,
       retweeted: false,
       lang: 'en' },
     { created_at: 'Sun Feb 17 23:02:25 +0000 2019',
       id: 1097270071129448400,
       id_str: '1097270071129448448',
       text:
        'RT @Auntienaj: Me &amp; @AlealiMay at @highsnobiety x @eBay pop up #AllStarWeekend https://t.co/jjpbt6HM8I',
       truncated: false,
       entities: [Object],
       extended_entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 14,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun Feb 17 23:01:23 +0000 2019',
       id: 1097269808826064900,
       id_str: '1097269808826064898',
       text:
        'RT @AndrewJenks: 1) As #AllStarWeekend continues, the murder of #JamesJordan (father of #MichaelJordan) remains covered up by judges &amp; othe…',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 1,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       lang: 'en' },
     { created_at: 'Sun Feb 17 23:00:45 +0000 2019',
       id: 1097269647911530500,
       id_str: '1097269647911530496',
       text:
        'Happy #AllStarWeekend y’all! Had to pay @HOMAGE #bringthesonicsback https://t.co/omB1yBa3S5',
       truncated: false,
       entities: [Object],
       extended_entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun Feb 17 23:00:22 +0000 2019',
       id: 1097269553615261700,
       id_str: '1097269553615261707',
       text:
        '1) As #AllStarWeekend continues, the murder of #JamesJordan (father of #MichaelJordan) remains covered up by judges… https://t.co/rGpmvKU0WF',
       truncated: true,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 1,
       favorite_count: 2,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun Feb 17 22:59:25 +0000 2019',
       id: 1097269315181727700,
       id_str: '1097269315181727746',
       text:
        '🏀who is waiting for all-star game? 🏀\n\n#AllStarWeekend #AllStarGame2019 #TeamLeBron #lakersnation #biggame https://t.co/cddP3judx5',
       truncated: false,
       entities: [Object],
       extended_entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun Feb 17 22:58:42 +0000 2019',
       id: 1097269132784033800,
       id_str: '1097269132784033793',
       text:
        'RT @BET: #StephCurry loses his crown to Joe Harris in NBA 3-point contest. #AllStarWeekend \nhttps://t.co/KBb7QUCZW4',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 4,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun Feb 17 22:58:32 +0000 2019',
       id: 1097269090173894700,
       id_str: '1097269090173894656',
       text:
        'RT @BET: #StephCurry loses his crown to Joe Harris in NBA 3-point contest. #AllStarWeekend \nhttps://t.co/KBb7QUCZW4',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source:
        '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 4,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' } ],
  search_metadata:
   { completed_in: 0.036,
     max_id: 1097270071129448400,
     max_id_str: '1097270071129448448',
     next_results:
      '?max_id=1096931683268476932&q=%23allstarweekend&lang=en&count=10&include_entities=1&result_type=mixed',
     query: '%23allstarweekend',
     refresh_url:
      '?since_id=1097270071129448448&q=%23allstarweekend&lang=en&result_type=mixed&include_entities=1',
     count: 10,
     since_id: 0,
     since_id_str: '0' } }