_events: [ Object ],
  _eventsCount: 5,
    _maxListeners: undefined,
      output: [],
        outputEncodings: [],
          outputCallbacks: [],
            outputSize: 0,
              writable: true,
                _last: true,
                  chunkedEncoding: false,
                    shouldKeepAlive: false,
                      useChunkedEncodingByDefault: false,
                        sendDate: false,
                          _removedConnection: false,
                            _removedContLen: false,
                              _removedTE: false,
                                _contentLength: 0,
                                  _hasBody: true,
                                    _trailer: '',
                                      finished: true,
                                        _headerSent: true,
                                          socket: [ Circular ],
                                            connection: [ Circular ],
                                              _header:
'GET /1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en HTTP/1.1\r\nAccept: */*\r\nConnection: close\r\nUser-Agent: node-twitter/1.7.1\r\nhost: api.twitter.com\r\nAuthorization: OAuth oauth_consumer_key="null",oauth_nonce="ffe0948d806c4d5184b749651a50fc9e",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1550447901",oauth_token="null",oauth_version="1.0",oauth_signature="5%2B8%2FK1PMJK4rJmIvaw7iUCDvfJ4%3D"\r\ncontent-length: 0\r\n\r\n',
  _onPendingData: [ Function: noopPendingOutput ],
    agent: [ Agent ],
      socketPath: undefined,
        timeout: undefined,
          method: 'GET',
            path:
'/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
  _ended: true,
    res: [ Circular ],
      aborted: false,
        timeoutCb: null,
          upgradeOrConnect: false,
            parser: null,
              maxHeadersCount: null,
                [ Symbol(isCorked) ]: false,
                  [ Symbol(outHeadersKey) ]: [ Object ] },
[ Symbol(res) ]:
TLSWrap {
  _parent: [ TCP ],
    _parentWrap: undefined,
      _secureContext: [ SecureContext ],
        reading: true,
          onread: [ Function: onStreamRead ],
            onhandshakestart: [ Function: noop ],
              onhandshakedone: [ Function: bound ],
                onocspresponse: [ Function: onocspresponse ],
                  onerror: [ Function: onerror ],
                    [ Symbol(owner) ]: [ Circular ]
},
[ Symbol(asyncId) ]: 4,
  [ Symbol(lastWriteQueueSize) ]: 0,
    [ Symbol(timeout) ]: null,
      [ Symbol(kBytesRead) ]: 0,
        [ Symbol(kBytesWritten) ]: 0,
          [ Symbol(connect - options) ]:
{
  rejectUnauthorized: true,
    ciphers:
  'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
    checkServerIdentity: [ Function: checkServerIdentity ],
      minDHSize: 1024,
        _events: [ Object ],
          _eventsCount: 3,
            _maxListeners: undefined,
              headers: [ Object ],
                method: 'get',
                  callback: [ Function ],
                    readable: true,
                      writable: true,
                        explicitMethod: true,
                          _qs: [ Querystring ],
                            _auth: [ Auth ],
                              _oauth: [ OAuth ],
                                _multipart: [ Multipart ],
                                  _redirect: [ Redirect ],
                                    _tunnel: [ Tunnel ],
                                      setHeader: [ Function ],
                                        hasHeader: [ Function ],
                                          getHeader: [ Function ],
                                            removeHeader: [ Function ],
                                              localAddress: undefined,
                                                pool: { },
  dests: [],
    __isRequestRequest: true,
      _callback: [ Function ],
        uri: [ Url ],
          proxy: null,
            tunnel: true,
              setHost: true,
                originalCookieHeader: undefined,
                  _disableCookies: true,
                    _jar: undefined,
                      port: 443,
                        host: 'api.twitter.com',
                          url: [ Url ],
                            path: null,
                              httpModule: [ Object ],
                                agentClass: [ Function: Agent ],
                                  agent: [ Agent ],
                                    _started: true,
                                      href:
  'https://api.twitter.com/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
    _defaultAgent: [ Agent ],
      servername: 'api.twitter.com',
        _agentKey: 'api.twitter.com:443::::::::::::::::::',
          encoding: null,
            singleUse: true
} },
connection:
TLSSocket {
  _tlsOptions:
  {
    pipe: false,
      secureContext: [ SecureContext ],
        isServer: false,
          requestCert: true,
            rejectUnauthorized: true,
              session: undefined,
                ALPNProtocols: undefined,
                  requestOCSP: undefined
  },
  _secureEstablished: true,
    _securePending: false,
      _newSessionPending: false,
        _controlReleased: true,
          _SNICallback: null,
            servername: 'api.twitter.com',
              alpnProtocol: false,
                authorized: true,
                  authorizationError: null,
                    encrypted: true,
                      _events:
  [ Object: null prototype ] {
    close: [ Array ],
      end: [ Function: onReadableStreamEnd ],
        secure: [ Function: onConnectSecure ],
          free: [ Function: onFree ],
            agentRemove: [ Function: onRemove ],
              drain: [ Function: ondrain ],
                error: [ Function: socketErrorListener ],
                  finish: [ Function ]
  },
  _eventsCount: 8,
    connecting: false,
      _hadError: false,
        _handle:
  TLSWrap {
    _parent: [ TCP ],
      _parentWrap: undefined,
        _secureContext: [ SecureContext ],
          reading: true,
            onread: [ Function: onStreamRead ],
              onhandshakestart: [ Function: noop ],
                onhandshakedone: [ Function: bound ],
                  onocspresponse: [ Function: onocspresponse ],
                    onerror: [ Function: onerror ],
                      [ Symbol(owner) ]: [ Circular ]
  },
  _parent: null,
    _host: 'api.twitter.com',
      _readableState:
  ReadableState {
    objectMode: false,
      highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
      pipes: null,
        pipesCount: 0,
          flowing: true,
            ended: false,
              endEmitted: false,
                reading: false,
                  sync: false,
                    needReadable: true,
                      emittedReadable: false,
                        readableListening: false,
                          resumeScheduled: false,
                            paused: false,
                              emitClose: false,
                                autoDestroy: false,
                                  destroyed: false,
                                    defaultEncoding: 'utf8',
                                      awaitDrain: 0,
                                        readingMore: true,
                                          decoder: null,
                                            encoding: null
  },
  readable: true,
    _maxListeners: undefined,
      _writableState:
  WritableState {
    objectMode: false,
      highWaterMark: 16384,
        finalCalled: true,
          needDrain: false,
            ending: true,
              ended: true,
                finished: false,
                  destroyed: false,
                    decodeStrings: false,
                      defaultEncoding: 'utf8',
                        length: 0,
                          writing: false,
                            corked: 0,
                              sync: false,
                                bufferProcessing: false,
                                  onwrite: [ Function: bound onwrite ],
                                    writecb: null,
                                      writelen: 0,
                                        bufferedRequest: null,
                                          lastBufferedRequest: null,
                                            pendingcb: 1,
                                              prefinished: false,
                                                errorEmitted: false,
                                                  emitClose: false,
                                                    autoDestroy: false,
                                                      bufferedRequestCount: 0,
                                                        corkedRequestsFree: [ Object ]
  },
  writable: false,
    allowHalfOpen: false,
      _sockname: null,
        _pendingData: null,
          _pendingEncoding: '',
            server: undefined,
              _server: null,
                ssl:
  TLSWrap {
    _parent: [ TCP ],
      _parentWrap: undefined,
        _secureContext: [ SecureContext ],
          reading: true,
            onread: [ Function: onStreamRead ],
              onhandshakestart: [ Function: noop ],
                onhandshakedone: [ Function: bound ],
                  onocspresponse: [ Function: onocspresponse ],
                    onerror: [ Function: onerror ],
                      [ Symbol(owner) ]: [ Circular ]
  },
  _requestCert: true,
    _rejectUnauthorized: true,
      parser: null,
        _httpMessage:
  ClientRequest {
    _events: [ Object ],
      _eventsCount: 5,
        _maxListeners: undefined,
          output: [],
            outputEncodings: [],
              outputCallbacks: [],
                outputSize: 0,
                  writable: true,
                    _last: true,
                      chunkedEncoding: false,
                        shouldKeepAlive: false,
                          useChunkedEncodingByDefault: false,
                            sendDate: false,
                              _removedConnection: false,
                                _removedContLen: false,
                                  _removedTE: false,
                                    _contentLength: 0,
                                      _hasBody: true,
                                        _trailer: '',
                                          finished: true,
                                            _headerSent: true,
                                              socket: [ Circular ],
                                                connection: [ Circular ],
                                                  _header:
    'GET /1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en HTTP/1.1\r\nAccept: */*\r\nConnection: close\r\nUser-Agent: node-twitter/1.7.1\r\nhost: api.twitter.com\r\nAuthorization: OAuth oauth_consumer_key="null",oauth_nonce="ffe0948d806c4d5184b749651a50fc9e",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1550447901",oauth_token="null",oauth_version="1.0",oauth_signature="5%2B8%2FK1PMJK4rJmIvaw7iUCDvfJ4%3D"\r\ncontent-length: 0\r\n\r\n',
      _onPendingData: [ Function: noopPendingOutput ],
        agent: [ Agent ],
          socketPath: undefined,
            timeout: undefined,
              method: 'GET',
                path:
    '/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
      _ended: true,
        res: [ Circular ],
          aborted: false,
            timeoutCb: null,
              upgradeOrConnect: false,
                parser: null,
                  maxHeadersCount: null,
                    [ Symbol(isCorked) ]: false,
                      [ Symbol(outHeadersKey) ]: [ Object ]
  },
  [ Symbol(res) ]:
  TLSWrap {
    _parent: [ TCP ],
      _parentWrap: undefined,
        _secureContext: [ SecureContext ],
          reading: true,
            onread: [ Function: onStreamRead ],
              onhandshakestart: [ Function: noop ],
                onhandshakedone: [ Function: bound ],
                  onocspresponse: [ Function: onocspresponse ],
                    onerror: [ Function: onerror ],
                      [ Symbol(owner) ]: [ Circular ]
  },
  [ Symbol(asyncId) ]: 4,
    [ Symbol(lastWriteQueueSize) ]: 0,
      [ Symbol(timeout) ]: null,
        [ Symbol(kBytesRead) ]: 0,
          [ Symbol(kBytesWritten) ]: 0,
            [ Symbol(connect - options) ]:
  {
    rejectUnauthorized: true,
      ciphers:
    'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
      checkServerIdentity: [ Function: checkServerIdentity ],
        minDHSize: 1024,
          _events: [ Object ],
            _eventsCount: 3,
              _maxListeners: undefined,
                headers: [ Object ],
                  method: 'get',
                    callback: [ Function ],
                      readable: true,
                        writable: true,
                          explicitMethod: true,
                            _qs: [ Querystring ],
                              _auth: [ Auth ],
                                _oauth: [ OAuth ],
                                  _multipart: [ Multipart ],
                                    _redirect: [ Redirect ],
                                      _tunnel: [ Tunnel ],
                                        setHeader: [ Function ],
                                          hasHeader: [ Function ],
                                            getHeader: [ Function ],
                                              removeHeader: [ Function ],
                                                localAddress: undefined,
                                                  pool: { },
    dests: [],
      __isRequestRequest: true,
        _callback: [ Function ],
          uri: [ Url ],
            proxy: null,
              tunnel: true,
                setHost: true,
                  originalCookieHeader: undefined,
                    _disableCookies: true,
                      _jar: undefined,
                        port: 443,
                          host: 'api.twitter.com',
                            url: [ Url ],
                              path: null,
                                httpModule: [ Object ],
                                  agentClass: [ Function: Agent ],
                                    agent: [ Agent ],
                                      _started: true,
                                        href:
    'https://api.twitter.com/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
      _defaultAgent: [ Agent ],
        servername: 'api.twitter.com',
          _agentKey: 'api.twitter.com:443::::::::::::::::::',
            encoding: null,
              singleUse: true
  }
},
httpVersionMajor: 1,
  httpVersionMinor: 1,
    httpVersion: '1.1',
      complete: true,
        headers:
{
  connection: 'close',
    'content-length': '62',
      'content-type': 'application/json; charset=utf-8',
        date: 'Sun, 17 Feb 2019 23:58:21 GMT',
          server: 'tsa_a',
            'set-cookie':
  [ 'personalization_id="v1_AZr/U0s3dWbepR9L7f4fHA=="; Max-Age=63072000; Expires=Tue, 16 Feb 2021 23:58:21 GMT; Path=/; Domain=.twitter.com',
    'guest_id=v1%3A155044790155639424; Max-Age=63072000; Expires=Tue, 16 Feb 2021 23:58:21 GMT; Path=/; Domain=.twitter.com' ],
    'strict-transport-security': 'max-age=631138519',
      'x-connection-hash': '5f83ccc67502204b263d8033500d11e3',
        'x-response-time': '7'
},
rawHeaders:
[ 'connection',
  'close',
  'content-length',
  '62',
  'content-type',
  'application/json; charset=utf-8',
  'date',
  'Sun, 17 Feb 2019 23:58:21 GMT',
  'server',
  'tsa_a',
  'set-cookie',
  'personalization_id="v1_AZr/U0s3dWbepR9L7f4fHA=="; Max-Age=63072000; Expires=Tue, 16 Feb 2021 23:58:21 GMT; Path=/; Domain=.twitter.com',
  'set-cookie',
  'guest_id=v1%3A155044790155639424; Max-Age=63072000; Expires=Tue, 16 Feb 2021 23:58:21 GMT; Path=/; Domain=.twitter.com',
  'strict-transport-security',
  'max-age=631138519',
  'x-connection-hash',
  '5f83ccc67502204b263d8033500d11e3',
  'x-response-time',
  '7' ],
  trailers: { },
rawTrailers: [],
  aborted: false,
    upgrade: false,
      url: '',
        method: null,
          statusCode: 401,
            statusMessage: 'Authorization Required',
              client:
TLSSocket {
  _tlsOptions:
  {
    pipe: false,
      secureContext: [ SecureContext ],
        isServer: false,
          requestCert: true,
            rejectUnauthorized: true,
              session: undefined,
                ALPNProtocols: undefined,
                  requestOCSP: undefined
  },
  _secureEstablished: true,
    _securePending: false,
      _newSessionPending: false,
        _controlReleased: true,
          _SNICallback: null,
            servername: 'api.twitter.com',
              alpnProtocol: false,
                authorized: true,
                  authorizationError: null,
                    encrypted: true,
                      _events:
  [ Object: null prototype ] {
    close: [ Array ],
      end: [ Function: onReadableStreamEnd ],
        secure: [ Function: onConnectSecure ],
          free: [ Function: onFree ],
            agentRemove: [ Function: onRemove ],
              drain: [ Function: ondrain ],
                error: [ Function: socketErrorListener ],
                  finish: [ Function ]
  },
  _eventsCount: 8,
    connecting: false,
      _hadError: false,
        _handle:
  TLSWrap {
    _parent: [ TCP ],
      _parentWrap: undefined,
        _secureContext: [ SecureContext ],
          reading: true,
            onread: [ Function: onStreamRead ],
              onhandshakestart: [ Function: noop ],
                onhandshakedone: [ Function: bound ],
                  onocspresponse: [ Function: onocspresponse ],
                    onerror: [ Function: onerror ],
                      [ Symbol(owner) ]: [ Circular ]
  },
  _parent: null,
    _host: 'api.twitter.com',
      _readableState:
  ReadableState {
    objectMode: false,
      highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
      pipes: null,
        pipesCount: 0,
          flowing: true,
            ended: false,
              endEmitted: false,
                reading: false,
                  sync: false,
                    needReadable: true,
                      emittedReadable: false,
                        readableListening: false,
                          resumeScheduled: false,
                            paused: false,
                              emitClose: false,
                                autoDestroy: false,
                                  destroyed: false,
                                    defaultEncoding: 'utf8',
                                      awaitDrain: 0,
                                        readingMore: true,
                                          decoder: null,
                                            encoding: null
  },
  readable: true,
    _maxListeners: undefined,
      _writableState:
  WritableState {
    objectMode: false,
      highWaterMark: 16384,
        finalCalled: true,
          needDrain: false,
            ending: true,
              ended: true,
                finished: false,
                  destroyed: false,
                    decodeStrings: false,
                      defaultEncoding: 'utf8',
                        length: 0,
                          writing: false,
                            corked: 0,
                              sync: false,
                                bufferProcessing: false,
                                  onwrite: [ Function: bound onwrite ],
                                    writecb: null,
                                      writelen: 0,
                                        bufferedRequest: null,
                                          lastBufferedRequest: null,
                                            pendingcb: 1,
                                              prefinished: false,
                                                errorEmitted: false,
                                                  emitClose: false,
                                                    autoDestroy: false,
                                                      bufferedRequestCount: 0,
                                                        corkedRequestsFree: [ Object ]
  },
  writable: false,
    allowHalfOpen: false,
      _sockname: null,
        _pendingData: null,
          _pendingEncoding: '',
            server: undefined,
              _server: null,
                ssl:
  TLSWrap {
    _parent: [ TCP ],
      _parentWrap: undefined,
        _secureContext: [ SecureContext ],
          reading: true,
            onread: [ Function: onStreamRead ],
              onhandshakestart: [ Function: noop ],
                onhandshakedone: [ Function: bound ],
                  onocspresponse: [ Function: onocspresponse ],
                    onerror: [ Function: onerror ],
                      [ Symbol(owner) ]: [ Circular ]
  },
  _requestCert: true,
    _rejectUnauthorized: true,
      parser: null,
        _httpMessage:
  ClientRequest {
    _events: [ Object ],
      _eventsCount: 5,
        _maxListeners: undefined,
          output: [],
            outputEncodings: [],
              outputCallbacks: [],
                outputSize: 0,
                  writable: true,
                    _last: true,
                      chunkedEncoding: false,
                        shouldKeepAlive: false,
                          useChunkedEncodingByDefault: false,
                            sendDate: false,
                              _removedConnection: false,
                                _removedContLen: false,
                                  _removedTE: false,
                                    _contentLength: 0,
                                      _hasBody: true,
                                        _trailer: '',
                                          finished: true,
                                            _headerSent: true,
                                              socket: [ Circular ],
                                                connection: [ Circular ],
                                                  _header:
    'GET /1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en HTTP/1.1\r\nAccept: */*\r\nConnection: close\r\nUser-Agent: node-twitter/1.7.1\r\nhost: api.twitter.com\r\nAuthorization: OAuth oauth_consumer_key="null",oauth_nonce="ffe0948d806c4d5184b749651a50fc9e",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1550447901",oauth_token="null",oauth_version="1.0",oauth_signature="5%2B8%2FK1PMJK4rJmIvaw7iUCDvfJ4%3D"\r\ncontent-length: 0\r\n\r\n',
      _onPendingData: [ Function: noopPendingOutput ],
        agent: [ Agent ],
          socketPath: undefined,
            timeout: undefined,
              method: 'GET',
                path:
    '/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
      _ended: true,
        res: [ Circular ],
          aborted: false,
            timeoutCb: null,
              upgradeOrConnect: false,
                parser: null,
                  maxHeadersCount: null,
                    [ Symbol(isCorked) ]: false,
                      [ Symbol(outHeadersKey) ]: [ Object ]
  },
  [ Symbol(res) ]:
  TLSWrap {
    _parent: [ TCP ],
      _parentWrap: undefined,
        _secureContext: [ SecureContext ],
          reading: true,
            onread: [ Function: onStreamRead ],
              onhandshakestart: [ Function: noop ],
                onhandshakedone: [ Function: bound ],
                  onocspresponse: [ Function: onocspresponse ],
                    onerror: [ Function: onerror ],
                      [ Symbol(owner) ]: [ Circular ]
  },
  [ Symbol(asyncId) ]: 4,
    [ Symbol(lastWriteQueueSize) ]: 0,
      [ Symbol(timeout) ]: null,
        [ Symbol(kBytesRead) ]: 0,
          [ Symbol(kBytesWritten) ]: 0,
            [ Symbol(connect - options) ]:
  {
    rejectUnauthorized: true,
      ciphers:
    'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
      checkServerIdentity: [ Function: checkServerIdentity ],
        minDHSize: 1024,
          _events: [ Object ],
            _eventsCount: 3,
              _maxListeners: undefined,
                headers: [ Object ],
                  method: 'get',
                    callback: [ Function ],
                      readable: true,
                        writable: true,
                          explicitMethod: true,
                            _qs: [ Querystring ],
                              _auth: [ Auth ],
                                _oauth: [ OAuth ],
                                  _multipart: [ Multipart ],
                                    _redirect: [ Redirect ],
                                      _tunnel: [ Tunnel ],
                                        setHeader: [ Function ],
                                          hasHeader: [ Function ],
                                            getHeader: [ Function ],
                                              removeHeader: [ Function ],
                                                localAddress: undefined,
                                                  pool: { },
    dests: [],
      __isRequestRequest: true,
        _callback: [ Function ],
          uri: [ Url ],
            proxy: null,
              tunnel: true,
                setHost: true,
                  originalCookieHeader: undefined,
                    _disableCookies: true,
                      _jar: undefined,
                        port: 443,
                          host: 'api.twitter.com',
                            url: [ Url ],
                              path: null,
                                httpModule: [ Object ],
                                  agentClass: [ Function: Agent ],
                                    agent: [ Agent ],
                                      _started: true,
                                        href:
    'https://api.twitter.com/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
      _defaultAgent: [ Agent ],
        servername: 'api.twitter.com',
          _agentKey: 'api.twitter.com:443::::::::::::::::::',
            encoding: null,
              singleUse: true
  }
},
_consuming: true,
  _dumped: false,
    req:
ClientRequest {
  _events:
  [ Object: null prototype ] {
    socket: [ Function ],
      response: [ Function: bound ],
        error: [ Function: bound ],
          drain: [ Function ],
            prefinish: [ Function: requestOnPrefinish ]
  },
  _eventsCount: 5,
    _maxListeners: undefined,
      output: [],
        outputEncodings: [],
          outputCallbacks: [],
            outputSize: 0,
              writable: true,
                _last: true,
                  chunkedEncoding: false,
                    shouldKeepAlive: false,
                      useChunkedEncodingByDefault: false,
                        sendDate: false,
                          _removedConnection: false,
                            _removedContLen: false,
                              _removedTE: false,
                                _contentLength: 0,
                                  _hasBody: true,
                                    _trailer: '',
                                      finished: true,
                                        _headerSent: true,
                                          socket:
  TLSSocket {
    _tlsOptions: [ Object ],
      _secureEstablished: true,
        _securePending: false,
          _newSessionPending: false,
            _controlReleased: true,
              _SNICallback: null,
                servername: 'api.twitter.com',
                  alpnProtocol: false,
                    authorized: true,
                      authorizationError: null,
                        encrypted: true,
                          _events: [ Object ],
                            _eventsCount: 8,
                              connecting: false,
                                _hadError: false,
                                  _handle: [ TLSWrap ],
                                    _parent: null,
                                      _host: 'api.twitter.com',
                                        _readableState: [ ReadableState ],
                                          readable: true,
                                            _maxListeners: undefined,
                                              _writableState: [ WritableState ],
                                                writable: false,
                                                  allowHalfOpen: false,
                                                    _sockname: null,
                                                      _pendingData: null,
                                                        _pendingEncoding: '',
                                                          server: undefined,
                                                            _server: null,
                                                              ssl: [ TLSWrap ],
                                                                _requestCert: true,
                                                                  _rejectUnauthorized: true,
                                                                    parser: null,
                                                                      _httpMessage: [ Circular ],
                                                                        [ Symbol(res) ]: [ TLSWrap ],
                                                                          [ Symbol(asyncId) ]: 4,
                                                                            [ Symbol(lastWriteQueueSize) ]: 0,
                                                                              [ Symbol(timeout) ]: null,
                                                                                [ Symbol(kBytesRead) ]: 0,
                                                                                  [ Symbol(kBytesWritten) ]: 0,
                                                                                    [ Symbol(connect - options) ]: [ Object ]
  },
  connection:
  TLSSocket {
    _tlsOptions: [ Object ],
      _secureEstablished: true,
        _securePending: false,
          _newSessionPending: false,
            _controlReleased: true,
              _SNICallback: null,
                servername: 'api.twitter.com',
                  alpnProtocol: false,
                    authorized: true,
                      authorizationError: null,
                        encrypted: true,
                          _events: [ Object ],
                            _eventsCount: 8,
                              connecting: false,
                                _hadError: false,
                                  _handle: [ TLSWrap ],
                                    _parent: null,
                                      _host: 'api.twitter.com',
                                        _readableState: [ ReadableState ],
                                          readable: true,
                                            _maxListeners: undefined,
                                              _writableState: [ WritableState ],
                                                writable: false,
                                                  allowHalfOpen: false,
                                                    _sockname: null,
                                                      _pendingData: null,
                                                        _pendingEncoding: '',
                                                          server: undefined,
                                                            _server: null,
                                                              ssl: [ TLSWrap ],
                                                                _requestCert: true,
                                                                  _rejectUnauthorized: true,
                                                                    parser: null,
                                                                      _httpMessage: [ Circular ],
                                                                        [ Symbol(res) ]: [ TLSWrap ],
                                                                          [ Symbol(asyncId) ]: 4,
                                                                            [ Symbol(lastWriteQueueSize) ]: 0,
                                                                              [ Symbol(timeout) ]: null,
                                                                                [ Symbol(kBytesRead) ]: 0,
                                                                                  [ Symbol(kBytesWritten) ]: 0,
                                                                                    [ Symbol(connect - options) ]: [ Object ]
  },
  _header:
  'GET /1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en HTTP/1.1\r\nAccept: */*\r\nConnection: close\r\nUser-Agent: node-twitter/1.7.1\r\nhost: api.twitter.com\r\nAuthorization: OAuth oauth_consumer_key="null",oauth_nonce="ffe0948d806c4d5184b749651a50fc9e",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1550447901",oauth_token="null",oauth_version="1.0",oauth_signature="5%2B8%2FK1PMJK4rJmIvaw7iUCDvfJ4%3D"\r\ncontent-length: 0\r\n\r\n',
    _onPendingData: [ Function: noopPendingOutput ],
      agent:
  Agent {
    _events: [ Object ],
      _eventsCount: 1,
        _maxListeners: undefined,
          defaultPort: 443,
            protocol: 'https:',
              options: [ Object ],
                requests: { },
    sockets: [ Object ],
      freeSockets: { },
    keepAliveMsecs: 1000,
      keepAlive: false,
        maxSockets: Infinity,
          maxFreeSockets: 256,
            maxCachedSessions: 100,
              _sessionCache: [ Object ]
  },
  socketPath: undefined,
    timeout: undefined,
      method: 'GET',
        path:
  '/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
    _ended: true,
      res: [ Circular ],
        aborted: false,
          timeoutCb: null,
            upgradeOrConnect: false,
              parser: null,
                maxHeadersCount: null,
                  [ Symbol(isCorked) ]: false,
                    [ Symbol(outHeadersKey) ]:
  [ Object: null prototype ] {
    accept: [ Array ],
      connection: [ Array ],
        'user-agent': [ Array ],
          host: [ Array ],
            authorization: [ Array ],
              'content-length': [ Array ]
  }
},
request:
Request {
  _events:
  [ Object: null prototype ] {
    error: [ Function: bound ],
      complete: [ Function: bound ],
        pipe: [ Function ],
          data: [ Function ],
            end: [ Function ]
  },
  _eventsCount: 5,
    _maxListeners: undefined,
      headers:
  {
    Accept: '*/*',
      Connection: 'close',
        'User-Agent': 'node-twitter/1.7.1',
          Authorization:
    'OAuth oauth_consumer_key="null",oauth_nonce="ffe0948d806c4d5184b749651a50fc9e",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1550447901",oauth_token="null",oauth_version="1.0",oauth_signature="5%2B8%2FK1PMJK4rJmIvaw7iUCDvfJ4%3D"',
      'content-length': 0
  },
  method: 'get',
    callback: [ Function ],
      readable: true,
        writable: true,
          explicitMethod: true,
            _qs:
  Querystring {
    request: [ Circular ],
      lib: [ Object ],
        useQuerystring: undefined,
          parseOptions: { },
    stringifyOptions: { }
  },
  _auth:
  Auth {
    request: [ Circular ],
      hasAuth: false,
        sentAuth: false,
          bearerToken: null,
            user: null,
              pass: null
  },
  _oauth: OAuth { request: [ Circular ], params: [ Object ] },
  _multipart:
  Multipart {
    request: [ Circular ],
      boundary: 'd687d270-dec7-4ef8-95e6-5cf2859e6c66',
        chunked: false,
          body: null
  },
  _redirect:
  Redirect {
    request: [ Circular ],
      followRedirect: true,
        followRedirects: true,
          followAllRedirects: false,
            followOriginalHttpMethod: false,
              allowRedirect: [ Function ],
                maxRedirects: 10,
                  redirects: [],
                    redirectsFollowed: 0,
                      removeRefererHeader: false
  },
  _tunnel:
  Tunnel {
    request: [ Circular ],
      proxyHeaderWhiteList: [ Array ],
        proxyHeaderExclusiveList: []
  },
  setHeader: [ Function ],
    hasHeader: [ Function ],
      getHeader: [ Function ],
        removeHeader: [ Function ],
          localAddress: undefined,
            pool: { },
  dests: [],
    __isRequestRequest: true,
      _callback: [ Function ],
        uri:
  Url {
    protocol: 'https:',
      slashes: true,
        auth: null,
          host: 'api.twitter.com',
            port: null,
              hostname: 'api.twitter.com',
                hash: null,
                  search: '?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
                    query: 'q=%23allstarweekend&count=10&result_type=mixed&lang=en',
                      pathname: '/1.1/search/tweets.json',
                        path:
    '/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
      href:
    'https://api.twitter.com/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en'
  },
  proxy: null,
    tunnel: true,
      setHost: true,
        originalCookieHeader: undefined,
          _disableCookies: true,
            _jar: undefined,
              port: 443,
                host: 'api.twitter.com',
                  url:
  Url {
    protocol: 'https:',
      slashes: true,
        auth: null,
          host: 'api.twitter.com',
            port: null,
              hostname: 'api.twitter.com',
                hash: null,
                  search: '?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
                    query: 'q=%23allstarweekend&count=10&result_type=mixed&lang=en',
                      pathname: '/1.1/search/tweets.json',
                        path:
    '/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
      href:
    'https://api.twitter.com/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en'
  },
  path:
  '/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
    httpModule:
  {
    Agent: [ Function: Agent ],
      globalAgent: [ Agent ],
        Server: [ Function: Server ],
          createServer: [ Function: createServer ],
            get: [ Function: get ],
              request: [ Function: request ]
  },
  agentClass: [ Function: Agent ],
    agent:
  Agent {
    _events: [ Object ],
      _eventsCount: 1,
        _maxListeners: undefined,
          defaultPort: 443,
            protocol: 'https:',
              options: [ Object ],
                requests: { },
    sockets: [ Object ],
      freeSockets: { },
    keepAliveMsecs: 1000,
      keepAlive: false,
        maxSockets: Infinity,
          maxFreeSockets: 256,
            maxCachedSessions: 100,
              _sessionCache: [ Object ]
  },
  _started: true,
    href:
  'https://api.twitter.com/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
    req:
  ClientRequest {
    _events: [ Object ],
      _eventsCount: 5,
        _maxListeners: undefined,
          output: [],
            outputEncodings: [],
              outputCallbacks: [],
                outputSize: 0,
                  writable: true,
                    _last: true,
                      chunkedEncoding: false,
                        shouldKeepAlive: false,
                          useChunkedEncodingByDefault: false,
                            sendDate: false,
                              _removedConnection: false,
                                _removedContLen: false,
                                  _removedTE: false,
                                    _contentLength: 0,
                                      _hasBody: true,
                                        _trailer: '',
                                          finished: true,
                                            _headerSent: true,
                                              socket: [ TLSSocket ],
                                                connection: [ TLSSocket ],
                                                  _header:
    'GET /1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en HTTP/1.1\r\nAccept: */*\r\nConnection: close\r\nUser-Agent: node-twitter/1.7.1\r\nhost: api.twitter.com\r\nAuthorization: OAuth oauth_consumer_key="null",oauth_nonce="ffe0948d806c4d5184b749651a50fc9e",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1550447901",oauth_token="null",oauth_version="1.0",oauth_signature="5%2B8%2FK1PMJK4rJmIvaw7iUCDvfJ4%3D"\r\ncontent-length: 0\r\n\r\n',
      _onPendingData: [ Function: noopPendingOutput ],
        agent: [ Agent ],
          socketPath: undefined,
            timeout: undefined,
              method: 'GET',
                path:
    '/1.1/search/tweets.json?q=%23allstarweekend&count=10&result_type=mixed&lang=en',
      _ended: true,
        res: [ Circular ],
          aborted: false,
            timeoutCb: null,
              upgradeOrConnect: false,
                parser: null,
                  maxHeadersCount: null,
                    [ Symbol(isCorked) ]: false,
                      [ Symbol(outHeadersKey) ]: [ Object ]
  },
  ntick: true,
    response: [ Circular ],
      originalHost: 'api.twitter.com',
        originalHostHeaderName: 'host',
          responseContent: [ Circular ],
            _destdata: true,
              _ended: true,
                _callbackCalled: true
},
toJSON: [ Function: responseToJSON ],
  caseless:
Caseless {
  dict:
  {
    connection: 'close',
      'content-length': '62',
        'content-type': 'application/json; charset=utf-8',
          date: 'Sun, 17 Feb 2019 23:58:21 GMT',
            server: 'tsa_a',
              'set-cookie': [ Array ],
                'strict-transport-security': 'max-age=631138519',
                  'x-connection-hash': '5f83ccc67502204b263d8033500d11e3',
                    'x-response-time': '7'
  }
},
body:
'{"errors":[{"code":89,"message":"Invalid or expired token."}]}' }